language: python
dist: xenial
install:
- pip install -r requirements.txt
script:
- pytest
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  api_key:
    secure: ibzg/AGyJHsF122JZfYrh4FKPkx57//GaPA/JA0mrlaw+1yiqKPbkbFudzoCq60KXAyUeCC+zvNTMzlXBDyuXSQXiq/u43R7YXzAi3QAeLn63uOpCrklR0w4HcGvAc/6Z/h9RWHFrE5ggLYGTy98pTCfjPnvhfQmY+nJ5CEkLoQt0MKLgfzpqIw6CQXddtPnguBmTvfP1ib+TmJ4wKVypCo1C2mLLUFhSR8HWywePlojM8wsPYPrbDV0WnllqV9ya2vu6l0f/zB/0fdel1KxEdw8sY1bXI/AJ3e5I9Xwzus8xBtHJiA/lhZKRoVr8KJypqTtUDsDGCjOt/50+Yo/axNuLOWir+VHkGH5xu6s5dyPPwJkxjffOofi4UaxN3Go61lcAJTOfem6i90bkLXGtW9Uq0DbjDne3ZqikotDm1mCjHNO3zz5dkpOeIR6NYXJi5pHbbRWEJHvY4qGTJWrcutlvOUcux1N0VgB29hRu5BsGIM66bO9Y3Ix3vo2/lik1euffIong3BXpWsn6WIyy6B7sgeBXxlWyux1c33rPmqNmGswVR7dNI/N9V81a4/ZVQr6ksxK+583knd3Ik1jnXh62fuB8jBjE+8s3ry9+VHBiYuuCc1K75P4fXm19CAbCpJR5upP3GciCvStfQDl8FfAFY+FTJ5+1OlCThC4MTE=
