language: python
dist: xenial
install:
- pip install -r requirements.txt
script:
- pytest
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  api_key:
    secure: EAImtEOJpqdNYiunX75F49n/kQFoP3p8wCZRWAHN1u2mFMJY05uTR53EdA+ZurGZo7exR0DPbhoM7jp47vRPT6x9LVPt3YGnS/+pYg5qfgtJFe/4Hn6vvf6CTjlQB8OWnm3cmdiTScqBUsJL3mqObtbXiHimt0d0qi8SX8RsM53/iWJPz4OMfSrq3iun+72hCiGojd1qd75d0/SPOHYHX6noIUkzQzin9c9uRw4Lg7ADCtmBynIRHWLEHrXh4MvFbZElhU9Pr1Xhr/5LIoDqfCh6lohqMsc5C4zgLs8P7WsXzhRfpJmEXNbok5QsA+XaZLTk4KyH7526WcktfCasMfN7qNSdfi01zF6mvJiFf+tuMcQBZ2BOyzIEooofUqRmAXH0UCtyZNQv3ifjqSM0I+Vz+LWB18gavv69qfB5UzOsSG0VnIoT0U5yv2A18/XW4JxtIxEK9/wiRQdaRNALw8COxyoe1YXc2pdzo+Xjed3Chy2+fr1/lhHFoNMOdrGFNjoddqDgKzi0i6FuLRN29nVQ9gTEXjFjnPqZQE5XYkY1mkHQWFnT2un/oNqs9NxRcFq4Tb89RwdpM7aZtIqIMoWDZzd7ANWEKSaiQ2SdDkDvtgXRLUyVpfigs0LPB5VGo3z3ZV8H/nu1B1nMc3PKPdcWXB2vbHVdshwABb1/4jc=
   app: mortgage-predict
