language: python
dist: xenial
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  - provider: heroku
    api_key:
      secure: q7HLr783XNYJYAWf+Jz+cou4AkW4QVQukIuy9svOseMSFprvTnXYVbib3ZsG4eutTr7ptpTrK73LQSuSZJTzYScJTyMyahgk9Ht7Sresh6bKTl7SY9sNceW6ODpCT2w+TOO4K5pHkclj082bu71arl3cFt6o5JPEDxHPEghsuKZPXGzrB29UOMgchIm2Nkb7qUZYyqTk3G6trw6Y4bRRJM9RVpwdFNSqqqhRblY1O/uC3MQkoNMjFpYWTjwzAC/wlH1i+Mc8U3neBdMjrESlnEU2Lyt75NQO6AazLP1/umwY4qlYcGmOwRlLZe1Ab2oqUDkqCOt0oVrvEK8AuJuIGuRDIcGzHE5quTUeRCOF7jsQNfxyb+O1RwlLhuPi0mPT7wTU4enpC5n2W20mHXZ/8RpCx9wKt8Q+FXxUl5KIxDFapsXzMBDTouMrLvKMoKCMg7/NbYVhPFvt2HpBtgzxyd+ihMNBNmbMUJw4zqm0qPGdvK27TR1KOqHm2DKwUmnXjJkSFqvaQCsu7psgozzg91iXoHz7IPIWuTf7IoU+1uq0TckLNQHWXOwuxtvcIGqV9Gt4jD4wohkxSnJLavAI0dZ+V0ezfDU+U1AN26bjGlueRzDHSY6MZXLmez3yeBn61mzq5V6wItKtZu6bPyHh9weDHiNlTk9vAAgHsxkquXw=
  app : mortgage-predict