language: python
dist: xenial
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  - provider: heroku
    api_key:
      secure:  pOGQOBlI/lWHsjsWN07g+y4otNw9UYev3EHO9+DxuEJMYH9TmdvO+j5LEaC7QWuWmBjo0zl/VeYqLRt/jcu1XiI6MAmIpTHZ/b0PdlzM7D+rqEghIw1XVs38qGPEqfBDIfJCEHE7LwurX9F3oN6KlfDjrX50F/bzGCnyIG9xcuu0EzsycAZbZwvO4+vvTMwUp89Edmxs7h2KkqvpRxWSWHZeR22DBxrMHxBr9yhfg9QJsVip7vfIoEkmvHPechLdFCmo1JLTjzS/Adma4iZ8QUVeL2KV7L6IyCdVYnTYKn14wtci7uhE/FY6R7L7nhgVI1y+Ow6zMeMBVm72a2G4m2cE93GXBbz68rih/83/Usu9JEjaMX/3oMriLe98p3QHD8VxOzJzyilCQtiByi1lD9udBTbzD0BKkm5kNUqv6xGp6VSquxMmeSVD+yetNatADKPyNTNvF8tBiFFUQ+JgqJcMemQqrsxx9J6UeAnapV0A8ngoUFmQBv3CkvdtaTIDxll2hX+l0Bmhi80ljpbrb73bybnxQ0QQrDLyL9PTaPfUt8MpuVsC2NcbddSFIdWxC/SSJ1qBnB0sVdHOetSTL/3VpNWguDWv6Ai6rlGaHtfKhbXp3AXb4lX8cCL6yN8KygAKYEHvo2vBVXB+3w2Hg6YUqd/YeIhVxIpvxOk1ZME=
    app : mortgage-predict