language: python
dist: xenial
install:
- pip install -r requirements.txt
script:
- pytest
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  - provider : heroku
    api_key:
      secure: T4XLXFi4rhOF/neTNZBAVfHd9ThOV1kmlYuoiQuZe8bymrjwyIUF8BMt+cIDmtfzY9veNL6z6KAlkP+/0epbgcGT69zmKmSkqQuoxU5k64MLrmCe35bxltN4SSEySBwAVgj233rZ2m78qhCygLbxLfdGhhLlt8PMbeNmJ3g6QYAi9cPLL8Pw3VooRM/lmMyw41fMypNawjkJK44TZh7u7BNxji7/zGxQHZ/52QJi2YApbGFAiDAX+c1qKxH2QwDon0s1Y5pTNjC7p0WYuSO/K5k8dKWPzxKIYCEGjv4tv/lsuZbJdNKYOx7CKOkjV0MIdVwP02TLFgnCImWWHqVPFiBK58vUGU1uGPvORwJ717eJb6atsKhcDeVY8AATu1WvbueWpPDXAXmdTHiJxmEfXvEuI2h4c/+W5Ru4+jPzVcNmyq1YccsgSFv+woKfACkBK7BN1QRzf3gXmwJdTdP9JuPTCnT6S2etzqOLv3cs7qS8vwutc/Rqtxn2Eo2tVSpYUg+VKpnHD/5a1zyBOkscqTyAiZwq3xQ3eQkXBX3uBn+D6ruCl95+6n3NOARVog3Dzuf38L3xyJQmg4aRrrp9VZnidHx0QtGCUCIkTB5WDzg25KzsrMhsVmBR1LJj4dq1b2r/etWVDmdprYwRxnu36n2pPsa/bkkI4yVE8uAWvqo=
   app : test-mortgage-xgboost